services:
  agent:
    build:
      context: .
      dockerfile: dockerfile.txt

    image: agent-core:test
    container_name: agent-core

    env_file:
      - .env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    network_mode: host

    stdin_open: true
    tty: true