FROM python:3.12-slim-bookworm

LABEL description="ai security agent"

ARG TARGETARCH=amd64

ENV PYTHONUNBUFFERED=1 \
    LLM_BASE_URL=http://host.docker.internal:1234 \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /app

COPY agent/requirements.txt* ./
RUN if [ -f requirements.txt ]; then \
        pip3 install --no-cache-dir --break-system-packages -r requirements.txt; \
    fi


COPY agent/system_prompt.md ./
COPY agent/skills/main_skills.md ./skills/main_skills.md
COPY agent/tools/tools.md ./tools/tools.md

# Скопировать исполняемый файл
#COPY bin/agent_core /usr/local/bin/agent_core

RUN useradd -m -u 1000 agent \
    && chown -R agent:agent /app
USER agent

# Выполнить при запуске контейнера
#ENTRYPOINT ["/usr/local/bin/agent_core"]