#Сборка
FROM rust:1.98.1-trixie AS builder

#Py среда для сборки и линковки
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3.13-dev \
    && rm -rf /var/lib/apt/lists/*  

WORKDIR /build/agent/agent_core

#Исходники для ядра
COPY agent/agent_core /build/agent/agent_core

#Подсосы
COPY agent/skills /build/agent/skills
COPY agent/tools /build/agent/tools
COPY agent/system_prompt.md /build/agent/system_prompt.md
COPY agent/guardrails /build/agent/guardrails

#Собрать без сохранения
##Обратная совместимость присутствует. Желательно закоментить это и раскоментить нормльную сборку
# RUN cargo build --release && cp target/release/agent_core /build/agent_core

#Собрать со схранением
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    --mount=type=cache,id=agent-target,target=/build/agent/agent_core/target \
    cargo build --release \
    && cp /build/agent/agent_core/target/release/agent_core /build/agent_core

# Сборка nuclei
FROM golang:1.24-alpine AS nuclei-builder
RUN apk add --no-cache git
RUN go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@v3.3.5


#Запуск агента
FROM python:3.13-slim-trixie

#Имя
LABEL description="Agent runtime test container"

#Переменные среды
ENV PYTHONUNBUFFERED=1
ENV RUST_BACKTRACE=1
ENV LC_ALL=C.UTF-8
ENV NUCLEI_TEMPLATES_PATH=/agent/tools/nuclei-templates

#Добавить необходимые библиотеки питону
RUN pip install --no-cache-dir requests bandit semgrep

# Установка пакетов для загрузки по http и распаковки zip архивов
RUN apt-get update && apt-get install -y \
    ca-certificates \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Nuclei с доступом из path
COPY --from=nuclei-builder /go/bin/nuclei /usr/local/bin/nuclei

#Рабочая область
WORKDIR /agent

# Загрузка шаблонов Nuclei (в tools?????)
RUN wget -q https://github.com/projectdiscovery/nuclei-templates/archive/refs/heads/main.zip -O /tmp/templates.zip \
    && unzip -q /tmp/templates.zip -d /agent/tools/ \
    && mv /agent/tools/nuclei-templates-main /agent/tools/nuclei-templates \
    && rm /tmp/templates.zip

#Изолятор
RUN mkdir -p /agent/workspace

#Его файлы на тест
COPY agent/agent_core/src /agent/workspace/self/agent_core
COPY agent/tools /agent/workspace/self/tools
COPY agent/guardrails /agent/workspace/self/guardrails
COPY agent/skills /agent/workspace/self/skills

#Взять собранный под контейнер ELF
COPY --from=builder /build/agent_core /agent/agent_core/agent_core

#Создание пользователя, выдача прав
RUN chmod +x /agent/agent_core/agent_core && useradd --create-home --uid 1000 agent && chown -R agent:agent /agent

#На будущее сделать agent только read

#Дальше пашешь ты
USER agent

#Запуск
ENTRYPOINT ["./agent_core/agent_core"]
CMD ["-D"]